baseURL = 'https://laisladelfaro.com/'
languageCode = 'es-es'
title = 'La isla del faro'
theme = "coyote"
paginator = 6
canonifyurls = true
enableRobotsTXT = true


[params.meta]
  favicon = true
  homeDescription = "Bienvenido a nuestra página de programación donde resolveremos retos de hackathon, hablaremos de noticias, compartiremos momentos y experiencias. ¡Únete a nosotros para una aventura en el mundo del código! Aumenta tus habilidades y comunícate con individuos como tú."
  author = "JotaGarciaz"
[outputs]
  home = ['html', 'json', 'rss','llms','llmsfull']
  section = ['html', 'rss']
  taxonomy = ['html']

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'blog'

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"

[HTTPCache]
  [HTTPCache.cache]
    [HTTPCache.cache.for]
      excludes = []
      includes = ['**']

[outputFormats.llms]
  baseName = "llms"
  isPlainText = true
  mediaType = "text/plain"
  rel = "alternate"
  root = true

[outputFormats.llmsfull]
  baseName = "llms-full"
  isPlainText = true
  mediaType = "text/plain"
  rel = "alternate"
  root = true