baseURL = 'https://laisladelfaro.com/'
languageCode = 'es-es'
title = 'La isla del faro'
theme = "coyote"
paginator = 6

[params.meta]
  favicon = true

[outputs]
  home = ['HTML', 'JSON']

[pagination]
  disableAliases = false
  pagerSize = 6
  path = 'posts'